In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [22]:
df = pd.read_csv('customer.csv')
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [3]:
df=df.iloc[:,2:]

In [4]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [8]:
X=df.drop('purchased',axis=1)
y=df['purchased']

In [9]:
X

     review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [11]:
X_train

     review education
49     Good        UG
25     Good    School
29  Average        UG
33     Good        PG
32  Average        UG
28     Poor    School
14     Poor        PG
38     Good    School
13  Average    School
2      Good        PG
31     Poor    School
42     Good        PG
47     Good        PG
34  Average    School
24  Average        PG
36     Good        UG
3      Good        PG
15     Poor        UG
20  Average    School
22     Poor        PG
30  Average        UG
9      Good        UG
44  Average        UG
40     Good    School
6      Good    School
41     Good        PG
26     Poor        PG
21  Average        PG
7      Poor    School
35     Poor    School
10     Good        UG
4   Average        UG
39     Poor        PG
48     Good        UG
8   Average        UG
11     Good        UG
12     Poor    School
27     Poor        PG
37  Average        PG
18     Good    School

In [13]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [14]:
X_train=oe.fit_transform(X_train)

In [15]:
X_train

array([[2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [2., 0.]])

In [16]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()

In [19]:
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)

In [20]:
y_train

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [23]:
s_df=df['gender']

In [25]:
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [28]:
pd.get_dummies(df,columns=['gender'],drop_first=True)

    age   review education purchased  gender_Male
0    30  Average    School        No        False
1    68     Poor        UG        No        False
2    70     Good        PG        No        False
3    72     Good        PG        No        False
4    16  Average        UG        No        False
5    31  Average    School       Yes        False
6    18     Good    School        No         True
7    60     Poor    School       Yes        False
8    65  Average        UG        No        False
9    74     Good        UG       Yes         True
10   98     Good        UG       Yes        False
11   74     Good        UG       Yes         True
12   51     Poor    School        No         True
13   57  Average    School        No        False
14   15     Poor        PG       Yes         True
15   75     Poor        UG        No         True
16   59     Poor        UG       Yes         True
17   22     Poor        UG       Yes        False
18   19     Good    School        No         True
19   97     Poor        PG       Yes         True
20   57  Average    School       Yes        False
21   32  Average        PG        No         True
22   18     Poor        PG       Yes        False
23   96     Good    School        No        False
24   16  Average        PG       Yes        False
25   57     Good    School        No        False
26   53     Poor        PG        No        False
27   69     Poor        PG        No        False
28   48     Poor    School        No         True
29   83  Average        UG       Yes        False
30   73  Average        UG        No         True
31   22     Poor    School       Yes        False
32   92  Average        UG       Yes         True
33   89     Good        PG       Yes        False
34   86  Average    School        No         True
35   74     Poor    School       Yes         True
36   34     Good        UG       Yes        False
37   94  Average        PG       Yes         True
38   45     Good    School        No        False
39   76     Poor        PG        No         True
40   39     Good    School        No         True
41   23     Good        PG       Yes         True
42   30     Good        PG       Yes        False
43   27     Poor        PG        No         True
44   77  Average        UG        No        False
45   61     Poor        PG       Yes         True
46   64     Poor        PG        No        False
47   38     Good        PG       Yes        False
48   39     Good        UG       Yes        False
49   25     Good        UG        No        False

In [29]:
X_train,X_test,y_train,y_test=train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2)

In [30]:
X_train

    age  gender   review education
43   27    Male     Poor        PG
2    70  Female     Good        PG
4    16  Female  Average        UG
16   59    Male     Poor        UG
1    68  Female     Poor        UG
0    30  Female  Average    School
35   74    Male     Poor    School
41   23    Male     Good        PG
7    60  Female     Poor    School
42   30  Female     Good        PG
25   57  Female     Good    School
48   39  Female     Good        UG
12   51    Male     Poor    School
27   69  Female     Poor        PG
36   34  Female     Good        UG
3    72  Female     Good        PG
32   92    Male  Average        UG
24   16  Female  Average        PG
11   74    Male     Good        UG
18   19    Male     Good    School
22   18  Female     Poor        PG
37   94    Male  Average        PG
44   77  Female  Average        UG
8    65  Female  Average        UG
39   76    Male     Poor        PG
29   83  Female  Average        UG
9    74    Male     Good        UG
28   48    Male     Poor    School
30   73    Male  Average        UG
47   38  Female     Good        PG
26   53  Female     Poor        PG
21   32    Male  Average        PG
38   45  Female     Good    School
19   97    Male     Poor        PG
10   98  Female     Good        UG
46   64  Female     Poor        PG
13   57  Female  Average    School
33   89  Female     Good        PG
17   22  Female     Poor        UG
45   61    Male     Poor        PG

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [46]:
ohe=OneHotEncoder(drop='first',sparse_output=False)

In [47]:
X_train_new=ohe.fit_transform(X_train[['gender']])

In [48]:
X_train_new.shape

(40, 1)

In [49]:
X_train.shape

(40, 4)

In [51]:
X_train_new

array([[1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.]])